/**
 * @description
 * Typed CMS fetch helpers for Payload CMS data access.
 * All helpers use the Payload local API via getPayload + config pattern.
 * Returns strongly typed results matching the generated payload-types.ts.
 *
 * Key features:
 * - Every helper accepts an optional `locale` param for bilingual content
 * - getHomepage(locale): Fetches homepage global (hero + layout blocks)
 * - getNavigation(locale): Fetches navigation global (utility links, primary nav, mega menu)
 * - getFooter(locale): Fetches footer global (columns, board links, quick links, newsletter)
 * - getPageBySlug(slug, locale): Fetches a page from pages collection by slug
 * - getLatestNews(limit, locale): Fetches news sorted by date desc
 * - getUpcomingEvents(limit, locale): Fetches future events sorted by date asc
 * - getStandardsByCategory(locale): Fetches standards grouped by category
 *
 * @dependencies
 * - payload: getPayload function for local API access
 * - @payload-config: Payload configuration
 *
 * @notes
 * - All helpers run server-side only (no 'use client')
 * - Use in server components and page routes only
 * - Wraps Payload local API calls with type-safe return values
 * - Errors are caught and return null/empty to prevent page crashes
 * - locale defaults to 'en' if not provided
 */
import { getPayload, type Where } from 'payload'
import config from '@payload-config'

// Note: payload-types.ts is auto-generated by Payload. These type imports
// will be available after running the dev server. For now we use type-safe
// inline references where the generated types don't exist yet.
import type {
  Homepage,
  Navigation,
  Footer,
  SearchConfig,
  AuthConfig,
  Page,
  News,
  Event,
  Standard,
  Board,
  Project,
  Consultation,
} from '@/payload-types'

/** Payload-compatible locale type matching the generated config */
export type PayloadLocale = 'en' | 'fr' | 'all'

/** Narrows a string locale to PayloadLocale, defaulting to 'en' */
export function toPayloadLocale(locale: string | undefined): PayloadLocale {
  if (locale === 'fr' || locale === 'all') return locale
  return 'en'
}

/**
 * Fetches the homepage global (hero + layout blocks).
 * Returns null if not configured yet.
 */
export async function getHomepage(locale: PayloadLocale = 'en'): Promise<Homepage | null> {
  try {
    const payload = await getPayload({ config })
    const homepage = await payload.findGlobal({
      slug: 'homepage',
      locale,
    })
    return homepage as unknown as Homepage
  } catch {
    return null
  }
}

/**
 * Fetches the navigation global.
 * Returns null if not configured yet.
 */
export async function getNavigation(locale: PayloadLocale = 'en'): Promise<Navigation | null> {
  try {
    const payload = await getPayload({ config })
    const navigation = await payload.findGlobal({
      slug: 'navigation',
      locale,
    })
    return navigation as unknown as Navigation
  } catch {
    return null
  }
}

/**
 * Fetches the branding global (logo per locale + alt).
 * Returns null when the global isn't populated — callers should fall
 * back to the text wordmark in that case.
 */
export async function getBranding(locale: PayloadLocale = 'en'): Promise<{
  logo?: { url?: string | null; alt?: string | null; width?: number | null; height?: number | null } | null
} | null> {
  try {
    const payload = await getPayload({ config })
    const branding = await payload.findGlobal({
      slug: 'branding',
      locale,
      depth: 1,
    })
    return branding as unknown as {
      logo?: { url?: string | null; alt?: string | null; width?: number | null; height?: number | null } | null
    }
  } catch {
    return null
  }
}

/**
 * Fetches the footer global.
 * Returns null if not configured yet.
 */
export async function getFooter(locale: PayloadLocale = 'en'): Promise<Footer | null> {
  try {
    const payload = await getPayload({ config })
    const footer = await payload.findGlobal({
      slug: 'footer',
      locale,
    })
    return footer as unknown as Footer
  } catch {
    return null
  }
}

/**
 * Fetches a page from the pages collection by slug.
 * Returns the page with hero + layout blocks, or null if not found.
 */
export async function getPageBySlug(slug: string, locale: PayloadLocale = 'en'): Promise<Page | null> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'pages',
      where: {
        slug: { equals: slug },
      },
      limit: 1,
      locale,
    })
    return (result.docs[0] as unknown as Page) || null
  } catch {
    return null
  }
}

/**
 * Fetches the latest news items sorted by publishedDate descending.
 */
export async function getLatestNews(limit = 3, locale: PayloadLocale = 'en'): Promise<News[]> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'news',
      sort: '-publishedDate',
      limit,
      locale,
    })
    return result.docs as unknown as News[]
  } catch {
    return []
  }
}

/**
 * Fetches upcoming events (future dates) sorted by date ascending.
 */
export async function getUpcomingEvents(limit = 5, locale: PayloadLocale = 'en'): Promise<Event[]> {
  try {
    const payload = await getPayload({ config })
    const now = new Date().toISOString()
    const result = await payload.find({
      collection: 'events',
      where: {
        date: { greater_than: now },
      },
      sort: 'date',
      limit,
      locale,
    })
    return result.docs as unknown as Event[]
  } catch {
    return []
  }
}

/**
 * Fetches all standards grouped by category.
 * Returns an object keyed by category with arrays of standards.
 */
export async function getStandardsByCategory(locale: PayloadLocale = 'en'): Promise<Record<string, Standard[]>> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'standards',
      limit: 100,
      sort: 'title',
      locale,
    })
    const standards = result.docs as unknown as Standard[]

    // Group by category
    const grouped: Record<string, Standard[]> = {}
    for (const standard of standards) {
      const category = standard.category || 'Uncategorized'
      if (!grouped[category]) {
        grouped[category] = []
      }
      grouped[category].push(standard)
    }
    return grouped
  } catch {
    return {}
  }
}

/**
 * Fetches the search-config global (popular tags, default filters).
 * Returns null if not configured yet.
 */
export async function getSearchConfig(locale: PayloadLocale = 'en'): Promise<SearchConfig | null> {
  try {
    const payload = await getPayload({ config })
    const searchConfig = await payload.findGlobal({
      slug: 'search-config',
      locale,
    })
    return searchConfig as unknown as SearchConfig
  } catch {
    return null
  }
}

// ── Board-specific helpers (Epic 6-9) ────────────────────────────────────

/**
 * Fetches a board by slug with all fields.
 */
export async function getBoardBySlug(slug: string, locale: PayloadLocale = 'en'): Promise<Board | null> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'boards',
      where: { slug: { equals: slug } },
      limit: 1,
      locale,
    })
    return (result.docs[0] as unknown as Board) || null
  } catch {
    return null
  }
}

/**
 * Fetches all boards (for generateStaticParams and board nav).
 */
export async function getAllBoards(locale: PayloadLocale = 'en'): Promise<Board[]> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'boards',
      limit: 100,
      sort: 'name',
      locale,
    })
    return result.docs as unknown as Board[]
  } catch {
    return []
  }
}

/**
 * Fetches the standards-setting boards/councils only — i.e. every board EXCEPT
 * RASOC, the oversight council. Per CLAUDE.md "RASOC Rules", RASOC must not
 * appear in board nav, the Active Projects sidebar, the open-consultations
 * filter, or the boards [board-slug] static-params set.
 *
 * The exclusion runs at the data layer (Payload `where` filter on the
 * non-localized `abbreviation` field) so it can't drift between locales —
 * the previous in-component `b.slug !== 'rasoc'` filter was matching the
 * EN slug literal and leaked RASOC into FR routes (#78).
 */
export async function getActiveBoards(locale: PayloadLocale = 'en'): Promise<Board[]> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'boards',
      where: { abbreviation: { not_equals: 'RASOC' } },
      limit: 100,
      sort: 'name',
      locale,
    })
    return result.docs as unknown as Board[]
  } catch {
    return []
  }
}

/**
 * Fetches projects filtered by board, with populated relationships.
 */
export async function getProjectsByBoard(boardId: number, limit = 20, locale: PayloadLocale = 'en'): Promise<Project[]> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'projects',
      where: { board: { equals: boardId } },
      sort: 'title',
      limit,
      depth: 2,
      locale,
    })
    return result.docs as unknown as Project[]
  } catch {
    return []
  }
}

/**
 * Fetches all active projects with populated board/standard relationships.
 */
export async function getAllActiveProjects(locale: PayloadLocale = 'en'): Promise<Project[]> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'projects',
      where: { status: { equals: 'Active' } },
      sort: 'title',
      limit: 200,
      depth: 2,
      locale,
    })
    return result.docs as unknown as Project[]
  } catch {
    return []
  }
}

/**
 * Fetches a project by slug with full depth.
 *
 * Project slugs are localized (per-locale text), but FR slugs aren't
 * fully seeded across the corpus yet (see #198 / QA-210). To stop FR
 * project URLs from 404'ing while the slug backfill is pending:
 *
 * 1. Try the requested locale first (the common path).
 * 2. If 0 docs and locale != 'en', re-query under EN to find the doc by
 *    its EN slug, then refetch with the requested locale so the returned
 *    record carries whichever localized strings DO exist (`fallback: true`
 *    in payload.config covers GETs but not WHERE clauses).
 * 3. If both queries fail, return null and let the page call notFound().
 *
 * Step 2 errors are swallowed defensively — the worst case is the same
 * null we'd return without the fallback.
 */
export async function getProjectBySlug(projectSlug: string, locale: PayloadLocale = 'en'): Promise<Project | null> {
  try {
    const payload = await getPayload({ config })
    const primary = await payload.find({
      collection: 'projects',
      where: { slug: { equals: projectSlug } },
      limit: 1,
      depth: 3,
      locale,
    })
    if (primary.docs[0]) return primary.docs[0] as unknown as Project

    if (locale !== 'en') {
      try {
        const fallback = await payload.find({
          collection: 'projects',
          where: { slug: { equals: projectSlug } },
          limit: 1,
          depth: 0,
          locale: 'en',
        })
        const fallbackDoc = fallback.docs[0]
        if (fallbackDoc) {
          const localized = await payload.findByID({
            collection: 'projects',
            id: fallbackDoc.id,
            depth: 3,
            locale,
          })
          return (localized as unknown as Project) ?? (fallbackDoc as unknown as Project)
        }
      } catch {
        // Fallback path failed; fall through to null.
      }
    }
    return null
  } catch {
    return null
  }
}

/**
 * Fetches a single news item by slug. Used by the /news/[slug] detail route.
 * Returns null if no published item with that slug exists.
 */
export async function getNewsBySlug(slug: string, locale: PayloadLocale = 'en'): Promise<News | null> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'news',
      where: { slug: { equals: slug } },
      limit: 1,
      depth: 2,
      locale,
    })
    return (result.docs[0] as unknown as News) || null
  } catch {
    return null
  }
}

/**
 * Fetches news items filtered by board, sorted newest first.
 */
export async function getNewsByBoard(boardId: number, limit = 4, locale: PayloadLocale = 'en'): Promise<News[]> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'news',
      where: { board: { equals: boardId } },
      sort: '-date',
      limit,
      locale,
    })
    return result.docs as unknown as News[]
  } catch {
    return []
  }
}

/**
 * Fetches upcoming events filtered by board, sorted by date ascending.
 */
export async function getEventsByBoard(boardId: number, limit = 3, locale: PayloadLocale = 'en'): Promise<Event[]> {
  try {
    const payload = await getPayload({ config })
    const now = new Date().toISOString()
    const result = await payload.find({
      collection: 'events',
      where: {
        and: [
          { board: { equals: boardId } },
          { date: { greater_than: now } },
        ],
      },
      sort: 'date',
      limit,
      locale,
    })
    return result.docs as unknown as Event[]
  } catch {
    return []
  }
}

/**
 * Fetches open consultations (deadline in the future), sorted by deadline ascending.
 */
export async function getOpenConsultations(locale: PayloadLocale = 'en'): Promise<Consultation[]> {
  try {
    const payload = await getPayload({ config })
    const now = new Date().toISOString()
    const result = await payload.find({
      collection: 'consultations',
      where: { deadline_date: { greater_than: now } },
      sort: 'deadline_date',
      limit: 100,
      depth: 2,
      locale,
    })
    return result.docs as unknown as Consultation[]
  } catch {
    return []
  }
}

/**
 * Fetches all consultations (including closed), sorted by deadline.
 */
export async function getAllConsultations(locale: PayloadLocale = 'en'): Promise<Consultation[]> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'consultations',
      sort: 'deadline_date',
      limit: 200,
      depth: 2,
      locale,
    })
    return result.docs as unknown as Consultation[]
  } catch {
    return []
  }
}

/**
 * Fetches the auth-config global (login labels, support info).
 * Returns null if not configured yet.
 */
export async function getAuthConfig(): Promise<AuthConfig | null> {
  try {
    const payload = await getPayload({ config })
    const authConfig = await payload.findGlobal({
      slug: 'auth-config',
    })
    return authConfig as unknown as AuthConfig
  } catch {
    return null
  }
}

/**
 * Fetches all standards (for filter dropdowns).
 */
export async function getAllStandards(locale: PayloadLocale = 'en'): Promise<Standard[]> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'standards',
      limit: 100,
      sort: 'name',
      locale,
    })
    return result.docs as unknown as Standard[]
  } catch {
    return []
  }
}

// ── Phase 2 helpers (Epics 12-14) ─────────────────────────────────────────

/**
 * Fetches a page by its full slug path (for catch-all [...slug] route).
 * Joins the slug segments with "/" to match the pages collection slug field.
 */
export async function getPageByFullSlug(slugSegments: string[]): Promise<Page | null> {
  const fullSlug = slugSegments.join('/')
  return getPageBySlug(fullSlug)
}

/**
 * Fetches board members filtered by board slug, with populated board relationship.
 * Returns members sorted by role priority (chair, vice-chair, voting-member, non-voting)
 * then by sortOrder, then by name.
 */
export async function getBoardMembersByBoardSlug(
  boardSlug: string,
): Promise<Array<Record<string, unknown>>> {
  try {
    const payload = await getPayload({ config })
    // First get the board by slug
    const boardResult = await payload.find({
      collection: 'boards',
      where: { slug: { equals: boardSlug } },
      limit: 1,
    })
    const board = boardResult.docs[0]
    if (!board) return []

    const result = await payload.find({
      collection: 'board-members',
      where: { board: { equals: board.id } },
      sort: 'sortOrder',
      limit: 100,
      depth: 2,
    })
    return result.docs as unknown as Array<Record<string, unknown>>
  } catch {
    return []
  }
}

// ── Epic 15-16: Document Workflow + Listings ──────────────────────────────

/**
 * Fetches documents for comment filtered by status.
 */
export async function getDocumentsForComment(
  status?: 'open' | 'closed',
): Promise<unknown[]> {
  try {
    const payload = await getPayload({ config })
    const where: Where = {}
    if (status) {
      where.status = { equals: status }
    }
    const result = await payload.find({
      collection: 'documents-for-comment',
      where,
      sort: 'sortOrder',
      limit: 200,
      depth: 2,
    })
    return result.docs
  } catch {
    return []
  }
}

/**
 * Fetches committees filtered by board slug, sorted by sortOrder then name.
 */
export async function getCommitteesByBoardSlug(
  boardSlug: string,
): Promise<Array<Record<string, unknown>>> {
  try {
    const payload = await getPayload({ config })
    const boardResult = await payload.find({
      collection: 'boards',
      where: { slug: { equals: boardSlug } },
      limit: 1,
    })
    const board = boardResult.docs[0]
    if (!board) return []

    const result = await payload.find({
      collection: 'committees',
      where: {
        and: [
          { board: { equals: board.id } },
          { status: { equals: 'active' } },
        ],
      },
      sort: 'sortOrder',
      limit: 100,
      depth: 1,
    })
    return result.docs as unknown as Array<Record<string, unknown>>
  } catch {
    return []
  }
}

/**
 * Fetches a standards section by slug with full depth for tabs and CTAs.
 */
export async function getStandardsSectionBySlug(
  slug: string,
): Promise<Record<string, unknown> | null> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'standards-sections',
      where: { slug: { equals: slug } },
      limit: 1,
      depth: 3,
    })
    return (result.docs[0] as unknown as Record<string, unknown>) || null
  } catch {
    return null
  }
}

/**
 * Fetches a document detail by slug with full depth for relationships.
 *
 * The `documents-for-comment` listing pages link by their own slug (e.g.
 * `ed-crypto-assets-dfc`). A paired `document-details` record may live
 * under that same slug (post-fix seed) OR under a legacy `dd-X` slug.
 * When the direct lookup misses, fall back to finding the paired record
 * via its `howToReply.ctaHref`, which embeds the dfc slug — stripped of
 * its trailing `-dfc` so closed-document ctaHrefs (which point at the
 * comments PDF, not /submit-comment/...) still match.
 */
export async function getDocumentDetailBySlug(slug: string): Promise<unknown | null> {
  try {
    const payload = await getPayload({ config })
    const direct = await payload.find({
      collection: 'document-details',
      where: { slug: { equals: slug } },
      limit: 1,
      depth: 2,
    })
    if (direct.docs[0]) return direct.docs[0]

    const stripped = slug.replace(/-dfc$/, '')
    const fallback = await payload.find({
      collection: 'document-details',
      where: { 'howToReply.ctaHref': { contains: stripped } },
      limit: 1,
      depth: 2,
    })
    return fallback.docs[0] || null
  } catch {
    return null
  }
}

/**
 * Fetches all standards sections (for generateStaticParams).
 */
export async function getAllStandardsSections(): Promise<Array<Record<string, unknown>>> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'standards-sections',
      limit: 20,
      sort: 'title',
    })
    return result.docs as unknown as Array<Record<string, unknown>>
  } catch {
    return []
  }
}

/**
 * Fetches effective dates for a standard slug.
 */
export async function getEffectiveDatesByStandard(
  standardSlug: string,
): Promise<Record<string, unknown> | null> {
  try {
    const payload = await getPayload({ config })
    // First find the standard
    const standardResult = await payload.find({
      collection: 'standards',
      where: { slug: { equals: standardSlug } },
      limit: 1,
    })
    const standard = standardResult.docs[0]
    if (!standard) return null

    const result = await payload.find({
      collection: 'effective-dates',
      where: { standard: { equals: standard.id } },
      limit: 1,
      depth: 2,
    })
    return (result.docs[0] as unknown as Record<string, unknown>) || null
  } catch {
    return null
  }
}

/**
 * Fetches paginated resources with optional filters.
 */
export async function getResources(params: {
  category?: string
  resourceType?: string
  sort?: string
  startDate?: string
  endDate?: string
  page?: number
  limit?: number
}): Promise<{ docs: unknown[]; totalDocs: number; totalPages: number; page: number }> {
  try {
    const payload = await getPayload({ config })
    const where: Where = {
      status: { equals: 'published' },
    }
    if (params.category) {
      where.category = { equals: params.category }
    }
    if (params.resourceType) {
      where.resourceType = { equals: params.resourceType }
    }
    if (params.startDate || params.endDate) {
      const dateFilter: Where[string] = {}
      if (params.startDate) dateFilter.greater_than_equal = params.startDate
      if (params.endDate) dateFilter.less_than_equal = params.endDate
      where.date = dateFilter
    }
    const sortField = params.sort === 'oldest' ? 'date' : '-date'
    const result = await payload.find({
      collection: 'resources',
      where,
      sort: sortField,
      page: params.page || 1,
      limit: params.limit || 10,
      depth: 1,
    })
    return {
      docs: result.docs,
      totalDocs: result.totalDocs,
      totalPages: result.totalPages,
      page: result.page || 1,
    }
  } catch {
    return { docs: [], totalDocs: 0, totalPages: 0, page: 1 }
  }
}

/**
 * Fetches paginated news with optional filters.
 */
export async function getNewsListing(params: {
  board?: string
  category?: string
  sort?: string
  startDate?: string
  endDate?: string
  page?: number
  limit?: number
  isVolunteerOpportunity?: boolean
}): Promise<{ docs: unknown[]; totalDocs: number; totalPages: number; page: number }> {
  try {
    const payload = await getPayload({ config })
    const where: Where = {}
    if (params.board) {
      where['board.slug'] = { equals: params.board }
    }
    if (params.category) {
      where.category = { equals: params.category }
    }
    if (params.isVolunteerOpportunity) {
      where.isVolunteerOpportunity = { equals: true }
    }
    if (params.startDate || params.endDate) {
      const dateFilter: Where[string] = {}
      if (params.startDate) dateFilter.greater_than_equal = params.startDate
      if (params.endDate) dateFilter.less_than_equal = params.endDate
      where.date = dateFilter
    }
    const sortField = params.sort === 'oldest' ? 'date' : '-date'
    const result = await payload.find({
      collection: 'news',
      where,
      sort: sortField,
      page: params.page || 1,
      limit: params.limit || 10,
      depth: 1,
    })
    return {
      docs: result.docs,
      totalDocs: result.totalDocs,
      totalPages: result.totalPages,
      page: result.page || 1,
    }
  } catch {
    return { docs: [], totalDocs: 0, totalPages: 0, page: 1 }
  }
}

/**
 * Fetches paginated events/meetings with timeframe filter.
 */
export async function getMeetingsListing(params: {
  board?: string
  timeframe?: 'upcoming' | 'past'
  page?: number
  limit?: number
}): Promise<{ docs: unknown[]; totalDocs: number; totalPages: number; page: number }> {
  try {
    const payload = await getPayload({ config })
    const now = new Date().toISOString()
    const where: Where = {}
    if (params.board) {
      where['board.slug'] = { equals: params.board }
    }
    if (params.timeframe === 'upcoming') {
      where.date = { greater_than_equal: now }
    } else {
      where.date = { less_than: now }
    }
    const sortField = params.timeframe === 'upcoming' ? 'date' : '-date'
    const result = await payload.find({
      collection: 'events',
      where,
      sort: sortField,
      page: params.page || 1,
      limit: params.limit || 10,
      depth: 1,
    })
    return {
      docs: result.docs,
      totalDocs: result.totalDocs,
      totalPages: result.totalPages,
      page: result.page || 1,
    }
  } catch {
    return { docs: [], totalDocs: 0, totalPages: 0, page: 1 }
  }
}

/**
 * Fetches all standards sections slugs (for generateStaticParams).
 */
export async function getAllStandardsSlugs(): Promise<string[]> {
  try {
    const payload = await getPayload({ config })
    const result = await payload.find({
      collection: 'standards',
      limit: 100,
      depth: 0,
    })
    return result.docs.map((s) => (s as unknown as { slug?: string }).slug || '').filter(Boolean)
  } catch {
    return []
  }
}
