/**
 * @description
 * Main Payload CMS configuration file.
 * Defines the database adapter (PostgreSQL via Drizzle),
 * rich text editor (Lexical), collections, and admin settings.
 *
 * @dependencies
 * - payload: Core CMS framework
 * - @payloadcms/db-postgres: PostgreSQL adapter via Drizzle ORM
 * - @payloadcms/richtext-lexical: Lexical rich text editor
 * - sharp: Image processing for uploads
 *
 * @notes
 * - Collections are imported from src/collections/
 * - The importMap.baseDir must match the src directory
 * - DATABASE_URI and PAYLOAD_SECRET must be set in .env
 * - push: true in dev auto-syncs schema without migration files (Drizzle push)
 * - For production, use `npx payload migrate` with migration files
 * - Migration files live in src/migrations/ (auto-generated by migrate:create)
 */
import path from 'path'
import { fileURLToPath } from 'url'
import { buildConfig } from 'payload'
import { postgresAdapter } from '@payloadcms/db-postgres'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import sharp from 'sharp'

import { Users } from './collections/Users'
import { Media } from './collections/Media'
import { Boards } from './collections/Boards'
import { Standards } from './collections/Standards'
import { Projects } from './collections/Projects'
import { Consultations } from './collections/Consultations'
import { News } from './collections/News'
import { Events } from './collections/Events'
import { Documents } from './collections/Documents'
import { DecisionSummaries } from './collections/DecisionSummaries'
import { Contacts } from './collections/Contacts'
import { Pages } from './collections/Pages'
import { Navigation } from './globals/Navigation'
import { Footer } from './globals/Footer'
import { Homepage } from './globals/Homepage'
import { SearchConfig } from './globals/SearchConfig'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

export default buildConfig({
  // Admin panel configuration
  admin: {
    user: Users.slug,
    importMap: {
      baseDir: path.resolve(dirname),
    },
  },

  // Collections define the data models
  collections: [
    Users,
    Media,
    Boards,
    Standards,
    Projects,
    Consultations,
    News,
    Events,
    Documents,
    DecisionSummaries,
    Contacts,
    Pages,
  ],

  // Globals for site-wide settings
  globals: [Navigation, Footer, Homepage, SearchConfig],

  // Rich text editor
  editor: lexicalEditor(),

  // Secret for JWT signing — must be set in .env
  secret: process.env.PAYLOAD_SECRET || '',

  // TypeScript output for auto-generated types
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },

  // Database adapter — PostgreSQL via Drizzle ORM
  // push: true → auto-sync schema in dev (no migration files needed)
  // For production: set push: false, use `npx payload migrate`
  db: postgresAdapter({
    pool: {
      connectionString: process.env.DATABASE_URI || '',
    },
    push: process.env.NODE_ENV !== 'production',
  }),

  // Image processing
  sharp,

  // Plugins will be added as needed (Meilisearch, etc.)
  plugins: [],
})
