/**
 * @description
 * Main Payload CMS configuration file.
 * Defines the database adapter (PostgreSQL via Drizzle),
 * rich text editor (Lexical), collections, globals, and admin settings.
 *
 * @dependencies
 * - payload: Core CMS framework
 * - @payloadcms/db-postgres: PostgreSQL adapter via Drizzle ORM
 * - @payloadcms/richtext-lexical: Lexical rich text editor
 * - sharp: Image processing for uploads
 *
 * @notes
 * - Collections are imported from src/collections/
 * - Globals are imported from src/globals/
 * - The importMap.baseDir must match the src directory
 * - DATABASE_URI and PAYLOAD_SECRET must be set in .env
 * - push: true in dev auto-syncs schema without migration files (Drizzle push)
 * - For production, use `npx payload migrate` with migration files
 * - Migration files live in src/migrations/ (auto-generated by migrate:create)
 * - Phase 2 collections added in Epic 11: BoardMembers, Committees, Resources,
 *   EffectiveDates, DocumentsForComment, DocumentDetails, FormSubmissions,
 *   JobPostings, StandardsSections
 * - Phase 2 global added in Epic 11: AuthConfig
 */
import path from 'path'
import { fileURLToPath } from 'url'
import { buildConfig } from 'payload'
import { postgresAdapter } from '@payloadcms/db-postgres'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import sharp from 'sharp'
// Seed available via: npx tsx src/seed/index.ts
// import { seed } from './seed'

// Epic 22: Scheduled publishing
import { initScheduledPublishing } from './admin/hooks/scheduled-publishing'

// Phase 1 collections
import { Users } from './collections/Users'
import { Media } from './collections/Media'
import { Boards } from './collections/Boards'
import { Standards } from './collections/Standards'
import { Projects } from './collections/Projects'
import { Consultations } from './collections/Consultations'
import { News } from './collections/News'
import { Events } from './collections/Events'
import { Documents } from './collections/Documents'
import { DecisionSummaries } from './collections/DecisionSummaries'
import { Contacts } from './collections/Contacts'
import { Pages } from './collections/Pages'

// Epic 24: Media library
import { MediaFolders } from './collections/MediaFolders'

// Phase 2 collections (Epic 11)
import { BoardMembers } from './collections/BoardMembers'
import { Committees } from './collections/Committees'
import { Resources } from './collections/Resources'
import { EffectiveDates } from './collections/EffectiveDates'
import { DocumentsForComment } from './collections/DocumentsForComment'
import { DocumentDetails } from './collections/DocumentDetails'
import { FormSubmissions } from './collections/FormSubmissions'
import { JobPostings } from './collections/JobPostings'
import { StandardsSections } from './collections/StandardsSections'
import { Redirects } from './collections/Redirects'

// Globals
import { Navigation } from './globals/Navigation'
import { Footer } from './globals/Footer'
import { Homepage } from './globals/Homepage'
import { SearchConfig } from './globals/SearchConfig'
import { AuthConfig } from './globals/AuthConfig'
import { SiteAlert } from './globals/SiteAlert'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

export default buildConfig({
  // Bilingual support — EN/FR locales (Epic 18)
  localization: {
    locales: [
      { label: 'English', code: 'en' },
      { label: 'Francais', code: 'fr' },
    ],
    defaultLocale: 'en',
    fallback: true,
  },

  // Admin panel configuration (Epic 22: custom Nav + Dashboard)
  admin: {
    user: Users.slug,
    importMap: {
      baseDir: path.resolve(dirname),
    },
    components: {
      Nav: '/admin/components/CustomNav',
      views: {
        dashboard: {
          Component: '/admin/views/Dashboard',
        },
        contentTree: {
          Component: '/admin/views/ContentTree',
          path: '/tree',
        },
        mediaLibrary: {
          Component: '/admin/views/MediaLibrary',
          path: '/media',
        },
        pageBuilder: {
          Component: '/admin/views/PageBuilder',
          path: '/builder/:id',
        },
        workbox: {
          Component: '/admin/views/Workbox',
          path: '/workbox',
        },
      },
    },
  },

  // Collections define the data models
  collections: [
    // Core
    Users,
    Media,
    MediaFolders,
    // Organization
    Boards,
    Standards,
    // Content
    Projects,
    Consultations,
    News,
    Events,
    Documents,
    DecisionSummaries,
    Contacts,
    Pages,
    // Phase 2 (Epic 11)
    BoardMembers,
    Committees,
    Resources,
    EffectiveDates,
    DocumentsForComment,
    DocumentDetails,
    FormSubmissions,
    JobPostings,
    StandardsSections,
    Redirects,
  ],

  // Globals for site-wide settings
  globals: [Navigation, Footer, Homepage, SearchConfig, AuthConfig, SiteAlert],

  // Rich text editor
  editor: lexicalEditor(),

  // Secret for JWT signing — must be set in .env
  secret: process.env.PAYLOAD_SECRET || '',

  // TypeScript output for auto-generated types
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },

  // Database adapter — PostgreSQL via Drizzle ORM
  // push: true → auto-sync schema in dev (no migration files needed)
  // For production: set push: false, use `npx payload migrate`
  db: postgresAdapter({
    pool: {
      connectionString: process.env.DATABASE_URI || '',
    },
    push: process.env.NODE_ENV !== 'production',
  }),

  // Image processing
  sharp,

  // Seed is available via: npx tsx src/seed/index.ts
  // Disabled in onInit to avoid blocking dev server startup
  // Epic 22: Initialize scheduled publishing (5-min interval)
  async onInit(payload) {
    initScheduledPublishing(payload)
  },

  // Plugins will be added as needed (Meilisearch, etc.)
  plugins: [],
})
